spring.application.name=order-service
server.port=${SERVER_PORT:8080}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.open-in-view=false
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${AUTH_SERVER_JWKS_URI:http://localhost:8080/auth/jwks}
product-service.base-url=${PRODUCT_SERVICE_BASE_URL:http://localhost:8081}
spring.rabbitmq.host=kebnekaise.lmq.cloudamqp.com
spring.rabbitmq.port=5671
spring.rabbitmq.username=lwcorksc
spring.rabbitmq.password=UtplsafwdsxFR9OdtJOLFooIpvrsQ7YX
spring.rabbitmq.virtual-host=lwcorksc
spring.rabbitmq.ssl.enabled=true
app.rabbitmq.email-queue=${EMAIL_QUEUE_NAME:email-order-confirmations}
server.forward-headers-strategy=framework
springdoc.swagger-ui.path=/orders/swagger-ui.html
springdoc.api-docs.path=/orders/v3/api-docs
springdoc.swagger-ui.config-url=/orders/v3/api-docs/swagger-config
springdoc.swagger-ui.url=/orders/v3/api-docs
